# extract-system-errors.ps1
# Generated by Claude (Sonnet 4.6) - Validated in Lab 05
# Requirement: Run in elevated PowerShell (Run as Administrator)

# PRIMARY - Console output, System log, last 24 hours
Get-WinEvent -FilterHashtable @{LogName='System'; Level=1,2; StartTime=(Get-Date).AddHours(-24)} `
    | Select-Object TimeCreated, Id, LevelDisplayName, ProviderName, Message `
    | Format-List

# VARIANT 1 - Export to CSV on Desktop
# Get-WinEvent -FilterHashtable @{LogName='System'; Level=1,2; StartTime=(Get-Date).AddHours(-24)} `
#     | Select-Object TimeCreated, Id, LevelDisplayName, ProviderName, Message `
#     | Export-Csv -Path "$env:USERPROFILE\Desktop\SystemErrors.csv" -NoTypeInformation

# VARIANT 2 - System + Application combined, sorted by time
# 'System','Application' | ForEach-Object {
#     Get-WinEvent -FilterHashtable @{LogName=$_; Level=1,2; StartTime=(Get-Date).AddHours(-24)}
# } | Select-Object TimeCreated, Id, LevelDisplayName, ProviderName, Message `
#   | Sort-Object TimeCreated | Format-List

# PARAMETER REFERENCE
# Level=1   Critical
# Level=2   Error
# Level=3   Warning
# Level=4   Information
# .AddHours(-24)  last 24 hours  - change to .AddDays(-7) for last 7 days
# FilterHashtable uses Windows log index - faster than Where-Object on large logs
# Format-List prevents Message text truncation
# Always remove/replace usernames and hostnames before uploading CSV to cloud AI tools
